---
all:
  children:
    ios:
      children:
        core:
          hosts:
            CORE1: {ansible_host: 10.0.50.1}
            CORE2: {ansible_host: 2.2.2.2}
        distribution:
          hosts:
            DIST1: {ansible_host: 3.3.3.3}
            DIST2: {ansible_host: 4.4.4.4}
        access:
          hosts:
            ACC1: {ansible_host: 10.0.10.4}
            ACC2: {ansible_host: 10.0.20.4}
            ACC3: {ansible_host: 10.0.30.4}
            ACC4: {ansible_host: 10.0.40.4}
    asa:
      hosts:
        ASAV-0: {ansible_host: 10.0.12.21}
