---
- name: Deploy access switch configs
  hosts: access
  gather_facts: false

  tasks:
    - name: Apply templated config
      cisco.ios.ios_config:
        src: "{{ playbook_dir }}/../templates/access_mgmt.j2"
      register: cfg

    - name: Save config
      cisco.ios.ios_config:
        save_when: always
      when: cfg.changed
