---
- name: Enable password encryption
  hosts: ios
  gather_facts: false
  tasks:
    - name: Set service password-encryption
      cisco.ios.ios_config:
        lines:
          - service password-encryption
        save_when: modified
